### ISSUE TITLE
Wrong win/lost attribution

### ISSUE THREAD

**Issue by nrv** [dansan/spring-replay-site#89] opened 2015-08-09 18:18 UTC
On that replay, the other team won the game : 

http://replays.springrts.com/replay/707ac755e1650f5bc7356b1dea59fd27/

**Comment by nrv** [comment] 2015-08-09 19:22
also on this one : http://replays.springrts.com/replay/57a4c755d3a925e4b767b62f3d689955/

**Comment by abma** [comment] 2015-08-11 09:04
TS compution shown is correct, so false attribution should be easy to find:

if it decreases, team has lost / increase = team has won.

**Comment by jamerlan** [comment] 2015-11-01 13:01
lol.. such an old bug... 
still present! example: http://replays.springrts.com/replay/8501365676f737dcc424e226e92033f7/
[teh]decay team lost - but replays website displays "won"

**Comment by Jamanno** [comment] 2016-01-03 22:47
still a bug.
http://replays.springrts.com/replay/369389562bc9bfde0987390007b035a9/
In my battle history it is marked as lost as well. 
I could provide more wrong battle results if needed.

**Comment by dansan** [comment] 2016-01-11 20:26
The statistics on the player and the match pages are not calculated using the data on the replay site, but by a service called SLDB (https://github.com/Yaribz/SLDB). It takes into account all matches it can see from the lobby - also matches that are not recorded on the replay site. It does also use the smurf database to associate multiple accounts that it thinks belong to the same user. If you wish to separate your data from that of another user, that ask in the springrts.com lobby server subforum for a SLDB account split. Not sure though who or if someone will do it, but you can try.

Anyway - the important information to take away from this thread is: **The replay site does not calculate any statistics about users at all!** It does only display what SLDB calculates.

**Comment by dansan** [comment] 2016-01-11 20:26
damn - wrong issue

**Comment by dansan** [comment] 2016-01-11 22:40
I checked the replays, and the problem is with the demofile (sdf). In the place where the winning allyteams are listed, there is just the one that is shown as winner. It's obvious it's wrong, but that's simply what's in the file…
I have manually corrected the four linked replays and will write a script that will go through all replays and check consistency with SLDB data and a fix to maintain it in the future.

**Comment by jamerlan** [comment] 2016-01-12 07:18
dansan, please report this "demo files bug" to engine devs if you didn't yet ;-)

**Comment by dansan** [comment] 2016-11-01 23:24
Forum thread: https://springrts.com/phpbb/viewtopic.php?f=71&t=35698
Engine issues: https://springrts.com/mantis/view.php?id=5384 https://springrts.com/mantis/view.php?id=4939

**Comment by dansan** [comment] 2016-11-09 22:04
Engine issue has been fixed for next release.
A temporary workaround is using SLDB TrueSkill data to guess the matches result.

**Closed by dansan** 2016-11-09 22:04 UTC
