### ISSUE TITLE
Allow new .sdfz archive demo extension to be uploaded

### ISSUE THREAD

**Issue by FabriceFABS** [dansan/spring-replay-site#93] opened 2016-03-01 19:20 UTC
New demo extension file with Spring 101.0, for instance : 20160229_002745_Knockout_v2_101.sdfz

All is in the title, to be added !

**Comment by abma** [comment] 2016-03-01 19:24
duplicate of #91

(description there sucks a bit, agreed)

**Closed by abma** 2016-03-01 19:24 UTC
